# Generated by Django 5.2.15 on 2026-09-01 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diagnosis', '0002_alter_diagnosisrecord_attention_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosisrecord',
            name='combined_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
