# Generated by Django 5.2.15 on 2026-09-11 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diagnosis', '0003_diagnosisrecord_combined_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosisrecord',
            name='panel_path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosisrecord',
            name='transformer_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
